const images={
 plain:'https://a-static.mlcdn.com.br/%7Bw%7Dx%7Bh%7D/espelho-retangular-90x60cm-parede-banheiro-quarto-sala-hall-design-moderno-sem-moldura-lopazzi/lopazzi/erl-90x60sp/9f2d2d20a0ad5d3f2b23119e0da1bc87.jpeg',
 backlit:'https://www.centroespejos.com/img/c/16.jpg',
 mdf1:'https://gomagcdn.ro/domains3/lalemn.ro/files/product/large/riflaj-mdf-stejar-deschis-293246.png',
 mdf2:'https://m.magazineluiza.com.br/a-static/420x420/painel-decorativo-ripado-mdf-em-barra-134x250cm-335m2-pa75-dalla-costa/movelnacaixa/32753-47275/e8fce7cd0406c487cb86dea23c28d263.jpeg',
 bamboo1:'https://junpropanel.com/wp-content/uploads/2023/05/junpro-bamboo-veneer-panel-2.jpg',
 bamboo2:'https://triopanels.com/cdn/shop/files/hf_20260416_192250_2dbab98b-ce12-4fa7-9c99-83510b777206.png?v=1778091575&width=1856',
 louver1:'https://images.prismic.io/boskyinterior/aMgl5GGNHVfTPPs9_image9.jpg?auto=format%2Ccompress&h=1000&rect=0%2C0%2C1024%2C1024&w=1000',
 louver2:'https://www.board.co.jp/dcms_media/image/91982015202.jpg'
};
const products=[
{id:'m1',cat:'mirrors',name:{ru:'Зеркало с боковой подсветкой',kz:'Бүйірлік жарықтандырылған айна',en:'Mirror with side lighting'},desc:{ru:'Мягкая LED-подсветка по контуру',kz:'Контур бойынша жұмсақ LED жарығы',en:'Soft LED lighting around the contour'},price:65000,img:images.backlit},
{id:'m2',cat:'mirrors',name:{ru:'Зеркало со световой полосой',kz:'Жарық жолағы бар айна',en:'Mirror with light strip'},desc:{ru:'Минималистичная световая линия',kz:'Минималистік жарық сызығы',en:'Minimal light line'},price:72000,img:images.backlit},
{id:'m3',cat:'mirrors',name:{ru:'Клеящееся зеркало',kz:'Жабыстырылатын айна',en:'Adhesive mirror'},desc:{ru:'Чистая форма без подсветки',kz:'Жарықсыз таза пішін',en:'Clean frameless form without lighting'},price:42000,img:images.plain},
{id:'p1',cat:'mdf',name:{ru:'МДФ панель «Linea»',kz:'«Linea» МДФ панелі',en:'MDF panel “Linea”'},desc:{ru:'2800 × 1000 мм • 5 цветов',kz:'2800 × 1000 мм • 5 түс',en:'2800 × 1000 mm • 5 colours'},price:28900,img:images.mdf1},
{id:'p2',cat:'mdf',name:{ru:'МДФ панель «Wave»',kz:'«Wave» МДФ панелі',en:'MDF panel “Wave”'},desc:{ru:'2800 × 1000 мм • 5 узоров',kz:'2800 × 1000 мм • 5 өрнек',en:'2800 × 1000 mm • 5 patterns'},price:31500,img:images.mdf2},
{id:'b1',cat:'bamboo',name:{ru:'Бамбук шпон «Natural»',kz:'«Natural» бамбук шпон панелі',en:'Bamboo veneer “Natural”'},desc:{ru:'2900 × 1150 мм • натуральная фактура',kz:'2900 × 1150 мм • табиғи фактура',en:'2900 × 1150 mm • natural texture'},price:44900,img:images.bamboo1},
{id:'b2',cat:'bamboo',name:{ru:'Бамбук шпон «Warm Oak»',kz:'«Warm Oak» бамбук шпон панелі',en:'Bamboo veneer “Warm Oak”'},desc:{ru:'2900 × 1150 мм • тёплый оттенок',kz:'2900 × 1150 мм • жылы реңк',en:'2900 × 1150 mm • warm tone'},price:46900,img:images.bamboo2},
{id:'l1',cat:'louvers',name:{ru:'Лувер «Vertical»',kz:'«Vertical» лувер',en:'Louver “Vertical”'},desc:{ru:'150 × 2900 мм • декоративная рейка',kz:'150 × 2900 мм • сәндік рейка',en:'150 × 2900 mm • decorative slat'},price:9900,img:images.louver1},
{id:'l2',cat:'louvers',name:{ru:'Лувер «Warm Oak»',kz:'«Warm Oak» лувер',en:'Louver “Warm Oak”'},desc:{ru:'150 × 2900 мм • натуральный оттенок',kz:'150 × 2900 мм • табиғи реңк',en:'150 × 2900 mm • natural tone'},price:11500,img:images.louver2}
];
const cats={mirrors:'Зеркала',mdf:'МДФ панели',bamboo:'Бамбук шпон панели',louvers:'Луверы'};
const translations={
ru:{navCatalog:'Каталог',navMeasure:'Бесплатный замер',navAbout:'О нас',cart:'Корзина',eyebrow:'ИНТЕРЬЕРНЫЕ МАТЕРИАЛЫ • НА ЗАКАЗ',heroTitle:'Материалы, которые <i>создают пространство.</i>',heroText:'Зеркала и декоративные панели на заказ — точный размер, выразительная отделка и профессиональный замер.',catalogBtn:'Смотреть каталог',measureBtn:'Бесплатный замер',categoriesTitle:'Категории',categoriesText:'Зеркала, МДФ, бамбук шпон и луверы — для цельного современного интерьера.',mirrors:'Зеркала',mirrorSub:'Конфигуратор • на заказ',mdf:'МДФ панели',bamboo:'Бамбук шпон панели',louvers:'Луверы',popular:'Популярные товары',chooseTitle:'Выберите свой <i>вариант.</i>',chooseText:'Укажите форму, размер и отделку — конфигуратор соберёт товар перед добавлением в корзину.',configBtn:'Открыть конфигуратор зеркал',b1:'Бесплатный замер',b1t:'Поможем снять размеры и подобрать решение под помещение.',b2:'Нестандартные размеры',b2t:'Изготавливаем панели и зеркала по вашим параметрам.',b3:'Большой выбор',b3t:'Цвета, узоры и материалы собраны в одном месте.',b4:'Под заказ',b4t:'Каждая конфигурация формируется индивидуально.',measureTitle:'Бесплатный замер <i>вашего пространства.</i>',measureText:'Оставьте контакты — мы свяжемся с вами и согласуем удобное время.',name:'Имя',phone:'Номер телефона',address:'Адрес / район',comment:'Комментарий',sendMeasure:'Заказать бесплатный замер',footer:'Зеркала и декоративные стеновые материалы на заказ.',total:'Итого',whatsapp:'Заказать в WhatsApp',all:'Все',add:'В корзину',remove:'Удалить',empty:'Корзина пока пуста.',accepted:'Заявка принята. Мы свяжемся с вами для подтверждения замера.',addMirror:'Добавить в корзину',mirrorConfig:'Конфигуратор зеркала',type:'Тип зеркала',shape:'Форма',width:'Ширина, мм',height:'Высота, мм',price:'Ориентировочная цена',adhesive:'Клеящееся',side:'С боковой подсветкой',strip:'Со световой полосой',rect:'Прямоугольник',square:'Квадрат',circle:'Круг',oval:'Овал',arch:'Арка',custom:'Нестандартная форма',orderEmpty:'Добавьте товары в корзину.'},
kz:{navCatalog:'Каталог',navMeasure:'Тегін өлшеу',navAbout:'Біз туралы',cart:'Себет',eyebrow:'ИНТЕРЬЕР МАТЕРИАЛДАРЫ • ТАПСЫРЫСПЕН',heroTitle:'Кеңістікті <i>жасайтын материалдар.</i>',heroText:'Тапсырыс бойынша айналар мен сәндік панельдер — дәл өлшем, сапалы әрлеу және кәсіби өлшеу.',catalogBtn:'Каталогты көру',measureBtn:'Тегін өлшеу',categoriesTitle:'Санаттар',categoriesText:'Айналар, МДФ, бамбук шпон панельдері және луверлер.',mirrors:'Айналар',mirrorSub:'Конфигуратор • тапсырыспен',mdf:'МДФ панельдері',bamboo:'Бамбук шпон панельдері',louvers:'Луверлер',popular:'Танымал тауарлар',chooseTitle:'Өзіңізге <i>лайықтысын таңдаңыз.</i>',chooseText:'Пішінін, өлшемін және әрлеуін таңдаңыз — тауарды себетке қоспас бұрын конфигурация жасаңыз.',configBtn:'Айна конфигураторын ашу',b1:'Тегін өлшеу',b1t:'Өлшемдерді алуға және шешім таңдауға көмектесеміз.',b2:'Стандартты емес өлшемдер',b2t:'Панельдер мен айналарды сіздің өлшемдеріңіз бойынша жасаймыз.',b3:'Үлкен таңдау',b3t:'Түстер, өрнектер және материалдар бір жерде.',b4:'Тапсырыспен',b4t:'Әр конфигурация жеке жасалады.',measureTitle:'Кеңістігіңізге <i>тегін өлшеу.</i>',measureText:'Байланыс деректерін қалдырыңыз — біз хабарласып, уақытты келісеміз.',name:'Аты',phone:'Телефон нөмірі',address:'Мекенжай / аудан',comment:'Пікір',sendMeasure:'Тегін өлшеуге тапсырыс беру',footer:'Тапсырыс бойынша айналар мен сәндік қабырға материалдары.',total:'Барлығы',whatsapp:'WhatsApp арқылы тапсырыс беру',all:'Барлығы',add:'Себетке қосу',remove:'Өшіру',empty:'Себет бос.',accepted:'Өтінім қабылданды. Өлшеуді растау үшін хабарласамыз.',addMirror:'Себетке қосу',mirrorConfig:'Айна конфигураторы',type:'Айна түрі',shape:'Пішіні',width:'Ені, мм',height:'Биіктігі, мм',price:'Болжамды баға',adhesive:'Жабыстырылатын',side:'Бүйірлік жарықтандыру',strip:'Жарық жолағымен',rect:'Тіктөртбұрыш',square:'Шаршы',circle:'Дөңгелек',oval:'Сопақ',arch:'Арка',custom:'Стандартты емес пішін',orderEmpty:'Себетке тауар қосыңыз.'},
en:{navCatalog:'Catalog',navMeasure:'Free measurement',navAbout:'About',cart:'Cart',eyebrow:'INTERIOR MATERIALS • MADE TO ORDER',heroTitle:'Materials that <i>shape your space.</i>',heroText:'Made-to-order mirrors and decorative panels — precise dimensions, refined finishes and professional measurement.',catalogBtn:'View catalog',measureBtn:'Free measurement',categoriesTitle:'Categories',categoriesText:'Mirrors, MDF, bamboo veneer panels and louvers for a complete modern interior.',mirrors:'Mirrors',mirrorSub:'Configurator • made to order',mdf:'MDF panels',bamboo:'Bamboo veneer panels',louvers:'Louvers',popular:'Popular products',chooseTitle:'Choose your <i>option.</i>',chooseText:'Select the shape, size and finish — the configurator builds the product before adding it to the cart.',configBtn:'Open mirror configurator',b1:'Free measurement',b1t:'We help measure the space and choose the right solution.',b2:'Custom dimensions',b2t:'Panels and mirrors can be made to your dimensions.',b3:'Wide selection',b3t:'Colours, patterns and materials in one place.',b4:'Made to order',b4t:'Every configuration is created individually.',measureTitle:'Free measurement for <i>your space.</i>',measureText:'Leave your details and we will contact you to arrange a convenient time.',name:'Name',phone:'Phone number',address:'Address / area',comment:'Comment',sendMeasure:'Request free measurement',footer:'Made-to-order mirrors and decorative wall materials.',total:'Total',whatsapp:'Order via WhatsApp',all:'All',add:'Add to cart',remove:'Remove',empty:'Your cart is empty.',accepted:'Request received. We will contact you to confirm the measurement.',addMirror:'Add to cart',mirrorConfig:'Mirror configurator',type:'Mirror type',shape:'Shape',width:'Width, mm',height:'Height, mm',price:'Estimated price',adhesive:'Adhesive',side:'Side lighting',strip:'Light strip',rect:'Rectangle',square:'Square',circle:'Circle',oval:'Oval',arch:'Arch',custom:'Custom shape',orderEmpty:'Add products to the cart.'}
};
let lang=localStorage.getItem('siteLang')||'ru';let filter='all';let cart=[];try{cart=JSON.parse(localStorage.getItem('siteCart')||'[]');if(!Array.isArray(cart))cart=[]}catch(e){cart=[]}
const $=s=>document.querySelector(s);const t=k=>(translations[lang]&&translations[lang][k])||translations.ru[k]||k;const money=n=>new Intl.NumberFormat(lang==='en'?'en-US':lang==='kz'?'kk-KZ':'ru-RU').format(n)+' ₸';
function productName(p){return p.name[lang]||p.name.ru}function productDesc(p){return p.desc[lang]||p.desc.ru}
function applyTranslations(){document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>{const key=el.dataset.t;const value=t(key);if(el.tagName==='LABEL'){const textNode=[...el.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(textNode)textNode.textContent=value+' '}else el.textContent=value});document.querySelectorAll('[data-t-html]').forEach(el=>el.innerHTML=t(el.dataset.tHtml));const placeholders={name:'name',phone:'phone',address:'address',comment:'comment'};Object.entries(placeholders).forEach(([name,key])=>{const el=document.querySelector(`[name="${name}"]`);if(el)el.placeholder=t(key)});render();}
function render(){const list=filter==='all'?products:products.filter(p=>p.cat===filter);$('#products').innerHTML=list.map(p=>`<article class="product"><img src="${p.img}" alt="${productName(p)}" loading="lazy"><div class="product-info"><h3>${productName(p)}</h3><p>${productDesc(p)}</p><div class="price">${money(p.price)} <button class="add" type="button" data-add="${p.id}">${t('add')}</button></div></div></article>`).join('');$('#filters').innerHTML=['all',...Object.keys(cats)].map(c=>`<button type="button" class="filter ${filter===c?'active':''}" data-filter="${c}">${c==='all'?t('all'):(translations[lang][c]||cats[c])}</button>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;render();document.querySelector('.products-section').scrollIntoView({behavior:'smooth'})});updateCart()}
function add(id,custom={}){const p=products.find(x=>x.id===id);if(!p)return;const key=id+'|'+(custom.details||'');const item=cart.find(x=>x.key===key);if(item)item.qty++;else cart.push({key,id,qty:1,details:custom.details||''});save();openDrawer()}
function save(){localStorage.setItem('siteCart',JSON.stringify(cart));updateCart()}
function updateCart(){const count=cart.reduce((a,x)=>a+x.qty,0);const total=cart.reduce((a,x)=>{const p=products.find(p=>p.id===x.id);return a+(p?p.price*x.qty:0)},0);$('#cartCount').textContent=count;$('#total').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);if(!p)return '';return `<div class="cart-row"><img src="${p.img}" alt="${productName(p)}"><div><b>${productName(p)}</b><br><small>${x.details||productDesc(p)}</small><div class="qty"><button type="button" data-dec="${x.key}">−</button><span>${x.qty}</span><button type="button" data-inc="${x.key}">+</button><button type="button" data-del="${x.key}">${t('remove')}</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join(''):`<p style="color:#777">${t('empty')}</p>`;document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>change(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>change(b.dataset.dec,-1));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.del);save()})}
function change(key,n){const x=cart.find(i=>i.key===key);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(i=>i.key!==key);save()}
function openDrawer(){$('#drawer').classList.add('open');$('#overlay').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
$('#openCart').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;
$('#whatsapp').onclick=()=>{if(!cart.length){alert(t('orderEmpty'));return}const lines=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `${productName(p)}${x.details?', '+x.details:''} — ${x.qty} шт`});const total=cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);const text=`Здравствуйте! Я с сайта. Вот список товаров, которые мне нужны:\n\n${lines.join('\n')}\n\nИтого товаров: ${money(total)}`;window.open('https://wa.me/77080098483?text='+encodeURIComponent(text),'_blank','noopener')};
function closeModal(){$('#modal').style.display='none'}$('#closeModal').onclick=closeModal;
function openConfigurator(){const typeLabels={adhesive:t('adhesive'),side:t('side'),strip:t('strip')};const shapeLabels={rect:t('rect'),square:t('square'),circle:t('circle'),oval:t('oval'),arch:t('arch'),custom:t('custom')};$('#modalContent').innerHTML=`<h2>${t('mirrorConfig')}</h2><img id="configPreview" class="config-preview" src="${images.backlit}" alt="Mirror"><div class="config-grid"><label>${t('type')}<select id="ct"><option value="adhesive">${typeLabels.adhesive}</option><option value="side" selected>${typeLabels.side}</option><option value="strip">${typeLabels.strip}</option></select></label><label>${t('shape')}<select id="cf"><option value="rect">${shapeLabels.rect}</option><option value="square">${shapeLabels.square}</option><option value="circle">${shapeLabels.circle}</option><option value="oval">${shapeLabels.oval}</option><option value="arch">${shapeLabels.arch}</option><option value="custom">${shapeLabels.custom}</option></select></label><label>${t('width')}<input id="cw" type="number" min="100" value="1200"></label><label>${t('height')}<input id="ch" type="number" min="100" value="800"></label></div><p id="cprice" style="margin:20px 0;font-weight:700">${t('price')}: ${money(65000)}</p><button id="addMirror" class="btn dark" type="button">${t('addMirror')}</button>`;$('#ct').onchange=updateConfig;$('#cf').onchange=updateConfig;$('#cw').oninput=updateConfig;$('#ch').oninput=updateConfig;$('#addMirror').onclick=()=>{const details=`${typeLabels[$('#ct').value]}, ${shapeLabels[$('#cf').value]}, ${$('#cw').value}×${$('#ch').value} мм`;add('m1',{details});closeModal()};$('#modal').style.display='grid';updateConfig()}
function updateConfig(){const type=$('#ct').value;const base=type==='adhesive'?42000:type==='strip'?72000:65000;$('#cprice').textContent=`${t('price')}: ${money(base)}`;$('#configPreview').src=type==='adhesive'?images.plain:images.backlit}
$('#config').onclick=openConfigurator;
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
$('#measureForm').onsubmit=e=>{e.preventDefault();$('#success').textContent=t('accepted');e.target.reset();};
$('#lang').value=lang;$('#lang').onchange=e=>{lang=e.target.value;localStorage.setItem('siteLang',lang);applyTranslations()};
applyTranslations();