const products=[
{id:'m1',cat:'mirrors',name:'Зеркало с боковой подсветкой',desc:'Тёплая LED-подсветка по контуру',price:65000,img:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=85'},
{id:'m2',cat:'mirrors',name:'Зеркало со световой полосой',desc:'Минималистичная световая линия',price:72000,img:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85'},
{id:'p1',cat:'mdf',name:'МДФ панель «Linea»',desc:'2800 × 1000 мм • 5 цветов',price:28900,img:'https://images.unsplash.com/photo-1618220924273-338d82d6b886?auto=format&fit=crop&w=900&q=85'},
{id:'p2',cat:'mdf',name:'МДФ панель «Wave»',desc:'2800 × 1000 мм • 5 узоров',price:31500,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85'},
{id:'b1',cat:'bamboo',name:'Бамбук шпон «Natural»',desc:'2900 × 1150 мм • натуральная фактура',price:44900,img:'https://images.unsplash.com/photo-1615529162924-f8605388461d?auto=format&fit=crop&w=900&q=85'},
{id:'b2',cat:'bamboo',name:'Бамбук шпон «Warm Oak»',desc:'2900 × 1150 мм • тёплый оттенок',price:46900,img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85'},
{id:'l1',cat:'louvers',name:'Лувер «Vertical»',desc:'150 × 2900 мм • декоративная рейка',price:9900,img:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85'},
{id:'l2',cat:'louvers',name:'Лувер «Oak»',desc:'150 × 2900 мм • натуральный оттенок',price:11500,img:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85'}];
const cats={mirrors:'Зеркала',mdf:'МДФ панели',bamboo:'Бамбук шпон',louvers:'Луверы'};let filter='all';let cart=JSON.parse(localStorage.getItem('formeCart')||'[]');const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
function render(){const list=filter==='all'?products:products.filter(p=>p.cat===filter);$('#products').innerHTML=list.map(p=>`<article class="product"><img src="${p.img}" alt="${p.name}"><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${money(p.price)} <button class="add" data-add="${p.id}">В корзину</button></div></div></article>`).join('');$('#filters').innerHTML=['all',...Object.keys(cats)].map(c=>`<button class="filter ${filter===c?'active':''}" data-filter="${c}">${c==='all'?'Все':cats[c]}</button>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});updateCart()}
function add(id,custom={}){const p=products.find(x=>x.id===id);const key=id+JSON.stringify(custom);let x=cart.find(i=>i.key===key);if(x)x.qty++;else cart.push({key,id,qty:1,...custom});save();openDrawer()}
function save(){localStorage.setItem('formeCart',JSON.stringify(cart));updateCart()}
function updateCart(){const count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id).price*x.qty),0);$('#cartCount').textContent=count;$('#total').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><img src="${p.img}" alt=""><div><b>${p.name}</b><br><small>${x.details||p.desc}</small><div class="qty"><button data-dec="${x.key}">−</button>${x.qty}<button data-inc="${x.key}">+</button><button data-del="${x.key}">Удалить</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join(''):'<p style="color:#777">Корзина пока пуста.</p>';document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>change(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>change(b.dataset.dec,-1));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.del);save()})}
function change(key,n){const x=cart.find(i=>i.key===key);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(i=>i.key!==key);save()}
function openDrawer(){$('#drawer').classList.add('open');$('#overlay').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
$('#openCart').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;
$('#whatsapp').onclick=()=>{if(!cart.length)return alert('Добавьте товары в корзину.');let lines=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `${p.name}${x.details?', '+x.details:''} — ${x.qty} шт`});const total=cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0);const text=`Здравствуйте! Я с сайта. Вот список товаров, которые мне нужны:\n\n${lines.join('\n')}\n\nИтого товаров: ${money(total)}`;window.open('https://wa.me/77080098483?text='+encodeURIComponent(text),'_blank')};
function modal(html){$('#modalContent').innerHTML=html;$('#modal').style.display='grid'}$('#closeModal').onclick=()=>$('#modal').style.display='none';
$('#config').onclick=()=>modal(`<h2>Конфигуратор зеркала</h2><img class="config-preview" src="${products[0].img}" alt="Зеркало"><div class="config-grid"><label>Тип<select id="ct"><option>Клеящееся</option><option selected>С боковой подсветкой</option><option>Со световой полосой</option></select></label><label>Форма<select id="cf"><option>Прямоугольник</option><option>Квадрат</option><option>Круг</option><option>Овал</option><option>Арка</option><option>Нестандартная форма</option></select></label><label>Ширина, мм<input id="cw" type="number" min="100" value="1200"></label><label>Высота, мм<input id="ch" type="number" min="100" value="800"></label></div><p id="cprice" style="margin:20px 0;font-weight:700">Ориентировочная цена: ${money(65000)}</p><button id="addMirror" class="btn dark">Добавить в корзину</button>`);$('#addMirror').onclick=()=>{const d=`${$('#ct').value}, ${$('#cf').value}, ${$('#cw').value}×${$('#ch').value} мм`;add('m1',{details:d});$('#modal').style.display='none'};
$('#measureForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);$('#success').textContent='Заявка принята. Мы свяжемся с вами для подтверждения замера.';e.target.reset()};
$('#lang').onchange=e=>{const l=e.target.value;const map={ru:{},kz:{},en:{}};if(l==='en'){document.querySelectorAll('nav a')[0].textContent='Catalog';document.querySelectorAll('nav a')[1].textContent='Free measurement';document.querySelectorAll('nav a')[2].textContent='About';document.querySelector('h1').innerHTML='Materials that <i>shape your space.</i>'}if(l==='kz'){document.querySelectorAll('nav a')[0].textContent='Каталог';document.querySelectorAll('nav a')[1].textContent='Тегін өлшеу';document.querySelectorAll('nav a')[2].textContent='Біз туралы';document.querySelector('h1').innerHTML='Кеңістікті <i>жасайтын материалдар.</i>'}if(l==='ru')location.reload()};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;document.querySelector('.products-section').scrollIntoView();render()});render();